apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apemind-computer.fullname" . }}-data
  labels:
    {{- include "apemind-computer.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
